server:
  port: 8099

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ProyectoFinal
      
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  queue:
    movie:
      name: movieQueue
    serie:
      name: serieQueue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
